/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics Book",
  "tagline": "Free, open-source textbook created by Javeria Nigar for the GIAIC Community",
  "favicon": "img/favicon.ico",
  "url": "https://physical-ai-humanoid-robotics-2zp6.vercel.app/",
  "baseUrl": "/",
  "organizationName": "Danishhshahid",
  "projectName": "Physical-AI-Humanoid-Robotics-Book",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/Danishhshahid/Physical-AI-Humanoid-Robotics-Book/tree/main/website",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV",
      "crossorigin": "anonymous"
    }
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Physical AI & Humanoid Robotics",
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Textbook"
        },
        {
          "href": "https://github.com/JaveriaNigar",
          "label": "Author (GitHub)",
          "position": "right"
        },
        {
          "href": "https://www.linkedin.com/in/javeria-nigar-252b312b5/",
          "label": "LinkedIn",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Chapters",
          "items": [
            {
              "label": "Chapter 1: Introduction",
              "to": "/docs/ch1-intro"
            },
            {
              "label": "Chapter 2: Humanoid Basics",
              "to": "/docs/ch2-humanoid"
            },
            {
              "label": "Chapter 3: ROS 2",
              "to": "/docs/ch3-ros2"
            },
            {
              "label": "Chapter 4: Simulation",
              "to": "/docs/ch4-sim"
            },
            {
              "label": "Chapter 5: VLA Systems",
              "to": "/docs/ch5-vla"
            },
            {
              "label": "Chapter 6: Capstone",
              "to": "/docs/ch6-capstone"
            }
          ]
        },
        {
          "title": "Community & Creator",
          "items": [
            {
              "label": "Author GitHub",
              "href": "https://github.com/JaveriaNigar"
            },
            {
              "label": "Author LinkedIn",
              "href": "https://www.linkedin.com/in/javeria-nigar-252b312b5/"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "ROS 2 Docs",
              "href": "https://docs.ros.org/en/humble/"
            },
            {
              "label": "Gazebo",
              "href": "https://gazebosim.org/docs"
            },
            {
              "label": "Ollama",
              "href": "https://ollama.ai"
            }
          ]
        }
      ],
      "copyright": "\n          MIT License © 2025 Created by <strong>Javeria Nigar</strong> for <strong>GIAIC Community</strong><br/>\n          <em>Physical AI & Humanoid Robotics Essentials</em><br/>\n          Built with Docusaurus | Hosted on GitHub Pages<br/>\n          <a href=\"https://github.com/GIAIC-Community/Physical-AI-Textbook/blob/master/LICENSE\">License</a>\n        "
    },
    "prism": {
      "additionalLanguages": [
        "bash",
        "python",
        "yaml"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "announcementBar": {
      "id": "announcement",
      "content": "Created by Javeria Nigar for GIAIC Community - Free Textbook for Humanoid Robotics & AI",
      "isCloseable": true
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
